[meta]
version = "0.1.0"

[project]
name = "optionz"
package = "optionz"
main_lang = "py"
version = "0.2.13"
version_date = "2018-03-18"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2016-2018"
description = "command line option processor"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/optionz"
state = "shared"
url = "https://jddixon.github.io/optionz"

[py]
test_dir = "tests"
packages = [ "optionz",]
package_dir = [ "src",]
py_modules = []
scripts = []
ext_modules = []
